version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextron
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: nextron
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - db
